<a href="https://colab.research.google.com/github/nirmal102002/project/blob/main/spamdetection2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing important Modules

In [ ]:

import pandas as pd
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
#from sklearn.feature_extraction.text import TfidfVectorizer


Reading the dataset


In [ ]:
#read the dataset
data=pd.read_csv('/content/spammail.csv')
print(data.head())
#word_list=data.drop(['Prediction','Email No.'],axis=1).columns.tolist()
#print(word_list)



  Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]


In [ ]:
#data=data1.where((pd.notnull(data1)))
#print(data)

Separate Target and feature variables

In [ ]:
#separate the features and target variable
x=data.drop(['Prediction','Email No.'],axis=1) #Features
y=data['Prediction'] #Target variable
print(y)

0       0
1       0
2       0
3       0
4       0
       ..
5167    0
5168    0
5169    1
5170    1
5171    0
Name: Prediction, Length: 5172, dtype: int64


In [ ]:
#split the data into training and testing sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
#x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
print(y_train)

3164    1
2067    0
4717    0
2505    0
2268    0
       ..
4426    0
466     0
3092    0
3772    1
860     1
Name: Prediction, Length: 4137, dtype: int64


In [ ]:
'''vectorizer=TfidfVectorizer()
x_train_vectorized = vectorizer.fit_transform(x_train)
y_train_vectorized= vectorizer.fit_transform(y_train)'''

AttributeError: 'int' object has no attribute 'lower'

***Training the Logistic Regression model***

In [ ]:
#training the logistic regression models
model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)

'model=LogisticRegression(max_iter=1000)\nmodel.fit(x_train,y_train)'

### `***Training Naive bayes Model***

In [ ]:
model=MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [ ]:
'''rf = RandomForestClassifier(n_estimators=100)  # n_estimators denotes the number of trees

# Fit the model
rf.fit(x_train, y_train)'''



'rf = RandomForestClassifier(n_estimators=100)  # n_estimators denotes the number of trees\n\n# Fit the model\nrf.fit(x_train, y_train)'

In [ ]:
'''dtree = DecisionTreeClassifier()

# Fit the model
dtree.fit(x_train, y_train)'''

'dtree = DecisionTreeClassifier()\n\n# Fit the model\ndtree.fit(x_train, y_train)'

In [ ]:
'''model = SVC(kernel='sigmoid')  # kernel can be 'linear', 'poly', 'rbf', 'sigmoid', etc.
#polynomial
#guassian
# Fit the model
model.fit(x_train, y_train)'''

"model = SVC(kernel='sigmoid')  # kernel can be 'linear', 'poly', 'rbf', 'sigmoid', etc.\n#polynomial\n#guassian\n# Fit the model\nmodel.fit(x_train, y_train)"

In [ ]:
y_pred=model.predict(x_test)
#np.set_printoptions(threshold=np.inf)

print(y_pred.tolist())

[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 

In [ ]:
prediction_on_training_data=model.predict(x_train)
accuracy_on_training_data=accuracy_score(y_train,prediction_on_training_data)
print(accuracy_on_training_data)

0.943437273386512


In [ ]:
prediction_on_test_data=model.predict(x_test)
accuracy_on_test_data=accuracy_score(y_test,prediction_on_test_data)
print(accuracy_on_test_data)

0.9545893719806763


In [ ]:
#calculate accuracy and confusion matrix
#accuracy=accuracy_score(y_test,y_pred)
#print(accuracy)
confusion_mat=confusion_matrix(y_test,y_pred)
tp,fp,fn,tn=confusion_mat[0][0],confusion_mat[0][1],confusion_mat[1][0],confusion_mat[1][1]

precision=tp/(tp+fp)
error_rate=(fp+fn)/(tp+tn+fp+fn)
recall=tp/(tp+fn)
accuracy=(tp+tn)/(tp+tn+fn+fp)

print(accuracy)
print(error_rate)
print(recall)
print(precision)
print(confusion_mat)

0.9545893719806763
0.04541062801932367
0.9832402234636871
0.952638700947226
[[704  35]
 [ 12 284]]


*Making of Predictive system*

In [ ]:
#making of predictive system
def create_feature_vector(text,word_list):
  words=text.split()


  feature_vector=np.zeros(len(word_list),dtype=int)
  for i,word in enumerate(word_list):
    feature_vector[i]=int(word in words)
  return feature_vector





In [ ]:

 """ user_input=input("Enter the text:")
  user_feature_vector=create_feature_vector(user_input,word_list)
  print(user_feature_vector)
  user_feature_vector=user_feature_vector.reshape(1,-1)
  print(user_feature_vector)
  prediction=model.predict(user_feature_vector)"""
user_input=input("enter the text")
word_list=data.drop(['Prediction','Email No.'],axis=1).columns.tolist()
user_feature_vector=pd.DataFrame([create_feature_vector(user_input,word_list)],columns=word_list)
#user_feature_vector=create_feature_vector(user_input,word_list)
#user_feature_vector=user_feature_vector.reshape(1,-1)
#print(user_feature_vector)
predicted_probabilities=model.predict_proba(user_feature_vector)

spam_probability=predicted_probabilities[0,1]



enter the textGIFT with boAt - Sale is Live Make your loved ones smile | Up to 80% o


In [ ]:
print(predicted_probabilities)
print(spam_probability)
threshold= 0.45
if spam_probability>=threshold:
  print("spam")
else:
  print("ham")


#prediction=model.predict(user_feature_vector)
#if prediction[0]==1:
#    print("spam")
#else:
#    print("ham")"""

[[0.67471015 0.32528985]]
0.32528985442299674
ham


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load the dataset
data = pd.read_csv('/content/mail_data (1).csv', encoding='latin-1')
print(data.head())

# Encode the target variable
data['Category'] = data['Category'].map({'ham': 0, 'spam': 1})

# Separate features and target
X = data['Message']
y = data['Category']

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and apply CountVectorizer
vectorizer = CountVectorizer()
X_train_vect = vectorizer.fit_transform(X_train)
X_test_vect = vectorizer.transform(X_test)

# Create and train the Decision Tree classifier
clf = DecisionTreeClassifier()
clf.fit(X_train_vect, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test_vect)

# Output the model's performance metrics
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))


  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
Accuracy: 0.9713004484304932
Confusion Matrix:
[[953  13]
 [ 19 130]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       966
           1       0.91      0.87      0.89       149

    accuracy                           0.97      1115
   macro avg       0.94      0.93      0.94      1115
weighted avg       0.97      0.97      0.97      1115

